create table account (
    id int8 generated by default as identity,
    birthday timestamp,
    description varchar(255),
    email varchar(40) not null,
    first_name varchar(100) not null,
    last_name varchar(100) not null,
    password varchar(40) not null,
    city_id int8,
    role_id int8 not null,
    account_status_id int8 not null,
    primary key (id)
                     );

create table account_status (
    id int8 generated by default as identity,
    name varchar(100) not null,
    primary key (id)
                                 );


create table city (
    id int8 generated by default as identity,
    name varchar(100) not null,
    country_id int8 not null,
    primary key (id)
                  );

create table country (
    id int8 generated by default as identity,
    name varchar(100) not null,
    primary key (id)
                     );

create table message (
    id int8 generated by default as identity,
    sending_date timestamp not null,
    text varchar(2048) not null,
    message_status_id int8 not null,
    receiver_id int8 not null,
    replied_message_id int8,
    sender_id int8 not null,
    primary key (id)
                     );

create table message_status (
    id int8 generated by default as identity,
    name varchar(100) not null,
    primary key (id)
                            );

create table relationship (
    sender int2 not null,
    second_acc_id int8 not null,
    first_acc_id int8 not null,
    relationship_status_id int8 not null,
    primary key (first_acc_id, second_acc_id)
                          );

create table relationship_status (
    id int8 generated by default as identity,
    name varchar(100) not null,
    primary key (id)
                                 );

create table role (
    id int8 generated by default as identity,
    name varchar(100) not null,
    primary key (id)
                  );

alter table if exists relationship
    add constraint UK_relationship_acc_ids
    unique (first_acc_id, second_acc_id);

alter table if exists account
    add constraint UK_account_email
    unique (email);

alter table if exists city
    add constraint UK_city_name
    unique (name);

alter table if exists country
    add constraint UK_country_name
    unique (name);

alter table if exists message_status
    add constraint UK_message_status_name
    unique (name);

alter table if exists relationship_status
    add constraint UK_relationship_status_name
    unique (name);

alter table if exists role
    add constraint UK_role_name
    unique (name);

alter table if exists account
    add constraint FK_account_city_id
    foreign key (city_id) references city;

alter table if exists account
    add constraint FK_account_role_id
    foreign key (role_id) references role;

alter table if exists account
    add constraint FK_account_account_status_id
    foreign key (account_status_id) references account_status;

alter table if exists city
    add constraint FK_city_country_id
    foreign key (country_id) references country;

alter table if exists message
    add constraint FK_message_message_status_id
    foreign key (message_status_id) references message_status;

alter table if exists message
    add constraint FK_message_receiver_id
    foreign key (receiver_id) references account;

alter table if exists message
    add constraint FK_message_replied_message_id
    foreign key (replied_message_id) references message;

alter table if exists message
    add constraint FK_message_sender_id
    foreign key (sender_id) references account;

alter table if exists relationship
    add constraint FK_relationship_first_acc_id
    foreign key (first_acc_id) references account;

alter table if exists relationship
    add constraint FK_relationship_second_acc_id
    foreign key (second_acc_id) references account;

alter table if exists relationship
    add constraint FK_relationship_rlship_status_id
    foreign key (relationship_status_id) references relationship_status;